[book]
title = "Structure and Interpretation of Computer Programs"
author = "Harold Abelson, Gerald Jay Sussman, Julie Sussman, and Duncan McGreggor"
description = "The LFE Edition of the Classic Scheme Book"
language = "en"

[build]
build-dir = "book"

[preprocessor.index]

[preprocessor.links]

[output.html]
default-theme = "lfe-pdp"
preferred-dark-theme = "lfe-pdp"
#google-analytics = "UA-38274766-4"
git-repository-url = "https://github.com/cnbbooks/lfe-sicp/"
mathjax-support = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.print]
enable = true

#[output.pdf]
#browser-binary-path = "/Users/oubiwann/Applications/Web/Google Chrome.app/Contents/MacOS/Google Chrome"

#[output.epub]
#cover-image = "src/images/cover-large.jpg"

[output.typst]

[output.typst.output]
format = "pdf"
	
